{
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "report@snyk.io",
            "DATE_PUBLIC": "2021-07-09T12:37:08.277597Z",
            "ID": "CVE-2021-23405",
            "STATE": "PUBLIC",
            "TITLE": "SQL Injection"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "pimcore/pimcore",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_affected": "<",
                                                "version_value": "10.0.7"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "credit": [
            {
                "lang": "eng",
                "value": "Daniele Scanu @SoterITSecurity"
            }
        ],
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "This affects the package pimcore/pimcore before 10.0.7. This issue exists due to the absence of check on the storeId parameter in the method collectionsActionGet and groupsActionGet method within the ClassificationstoreController class."
                }
            ]
        },
        "impact": {
            "cvss": {
                "attackComplexity": "LOW",
                "attackVector": "NETWORK",
                "availabilityImpact": "LOW",
                "baseScore": 8.3,
                "baseSeverity": "HIGH",
                "confidentialityImpact": "HIGH",
                "integrityImpact": "HIGH",
                "privilegesRequired": "LOW",
                "scope": "UNCHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:L/E:F/RL:O/RC:C",
                "version": "3.1"
            }
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "SQL Injection"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://snyk.io/vuln/SNYK-PHP-PIMCOREPIMCORE-1316297",
                    "refsource": "MISC",
                    "url": "https://snyk.io/vuln/SNYK-PHP-PIMCOREPIMCORE-1316297"
                },
                {
                    "name": "https://github.com/pimcore/pimcore/pull/9572",
                    "refsource": "MISC",
                    "url": "https://github.com/pimcore/pimcore/pull/9572"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "report@snyk.io",
                "ID": "CVE-2021-23405"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "This affects the package pimcore/pimcore before 10.0.7. This issue exists due to the absence of check on the storeId parameter in the method collectionsActionGet and groupsActionGet method within the ClassificationstoreController class."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://snyk.io/vuln/SNYK-PHP-PIMCOREPIMCORE-1316297",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://snyk.io/vuln/SNYK-PHP-PIMCOREPIMCORE-1316297"
                    },
                    {
                        "name": "https://github.com/pimcore/pimcore/pull/9572",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://github.com/pimcore/pimcore/pull/9572"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-07-09T13:15Z",
        "publishedDate": "2021-07-09T13:15Z"
    }
}